// <auto-generated />
using System;
using DeIdeas.RouteFlow.API.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeIdeas.RouteFlow.API.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251201175136_Update_App")]
    partial class Update_App
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeIdeas.RouteFlow.API.DAL.Models.ModuleUser.USR_Config", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.ToTable("USR_Config", "ONE");
                });

            modelBuilder.Entity("DeIdeas.RouteFlow.API.DAL.Models.ModuleUser.USR_Control", b =>
                {
                    b.Property<int>("IdControl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdControl"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("IdMaestro")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdControl");

                    b.HasIndex("User");

                    b.ToTable("USR_Control", "ONE");
                });

            modelBuilder.Entity("DeIdeas.RouteFlow.API.DAL.Models.ModuleUser.USR_ControlRol", b =>
                {
                    b.Property<int>("IdControl")
                        .HasColumnType("int");

                    b.Property<string>("Rol")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("IdControl", "Rol");

                    b.HasIndex("Rol");

                    b.ToTable("USR_ControlRol", "ONE");
                });

            modelBuilder.Entity("DeIdeas.RouteFlow.API.DAL.Models.ModuleUser.USR_DetTypeUser", b =>
                {
                    b.Property<string>("User")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdTypeUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("User", "IdTypeUser");

                    b.HasIndex("IdTypeUser");

                    b.ToTable("USR_DetTypeUser", "ONE");
                });

            modelBuilder.Entity("DeIdeas.RouteFlow.API.DAL.Models.ModuleUser.USR_Rol", b =>
                {
                    b.Property<string>("Rol")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Rol");

                    b.ToTable("USR_Rol", "ONE");
                });

            modelBuilder.Entity("DeIdeas.RouteFlow.API.DAL.Models.ModuleUser.USR_TypeUser", b =>
                {
                    b.Property<int>("IdTypeUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTypeUser"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("IdTypeUser");

                    b.ToTable("USR_TypeUser", "ONE");
                });

            modelBuilder.Entity("DeIdeas.RouteFlow.API.DAL.Models.ModuleUser.USR_User", b =>
                {
                    b.Property<string>("User")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AdObjectId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ADObjectId");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<int>("IdTypeUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("USR_TypeUserIdTypeUser")
                        .HasColumnType("int");

                    b.HasKey("User");

                    b.HasIndex("AdObjectId")
                        .IsUnique();

                    b.HasIndex("IdTypeUser");

                    b.HasIndex("USR_TypeUserIdTypeUser");

                    b.ToTable("USR_User", "ONE");
                });

            modelBuilder.Entity("DeIdeas.RouteFlow.API.DAL.Models.ModuleUser.USR_UserRol", b =>
                {
                    b.Property<string>("User")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rol")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("RolNavigationRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserNavigationUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("User", "Rol");

                    b.HasIndex("Rol");

                    b.HasIndex("RolNavigationRol");

                    b.HasIndex("UserNavigationUser");

                    b.ToTable("USR_UserRol", "ONE");
                });

            modelBuilder.Entity("DeIdeas.RouteFlow.API.DAL.Models.ModuleUser.USR_Config", b =>
                {
                    b.HasOne("DeIdeas.RouteFlow.API.DAL.Models.ModuleUser.USR_User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeIdeas.RouteFlow.API.DAL.Models.ModuleUser.USR_Control", b =>
                {
                    b.HasOne("DeIdeas.RouteFlow.API.DAL.Models.ModuleUser.USR_User", "UserNavigation")
                        .WithMany()
                        .HasForeignKey("User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("DeIdeas.RouteFlow.API.DAL.Models.ModuleUser.USR_ControlRol", b =>
                {
                    b.HasOne("DeIdeas.RouteFlow.API.DAL.Models.ModuleUser.USR_Control", "Control")
                        .WithMany()
                        .HasForeignKey("IdControl")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DeIdeas.RouteFlow.API.DAL.Models.ModuleUser.USR_Rol", "RolNavigation")
                        .WithMany()
                        .HasForeignKey("Rol")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Control");

                    b.Navigation("RolNavigation");
                });

            modelBuilder.Entity("DeIdeas.RouteFlow.API.DAL.Models.ModuleUser.USR_DetTypeUser", b =>
                {
                    b.HasOne("DeIdeas.RouteFlow.API.DAL.Models.ModuleUser.USR_TypeUser", "TypeUser")
                        .WithMany()
                        .HasForeignKey("IdTypeUser")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DeIdeas.RouteFlow.API.DAL.Models.ModuleUser.USR_User", "UserNavigation")
                        .WithMany()
                        .HasForeignKey("User")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TypeUser");

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("DeIdeas.RouteFlow.API.DAL.Models.ModuleUser.USR_User", b =>
                {
                    b.HasOne("DeIdeas.RouteFlow.API.DAL.Models.ModuleUser.USR_TypeUser", "TypeUser")
                        .WithMany()
                        .HasForeignKey("IdTypeUser")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DeIdeas.RouteFlow.API.DAL.Models.ModuleUser.USR_TypeUser", null)
                        .WithMany("Users")
                        .HasForeignKey("USR_TypeUserIdTypeUser");

                    b.Navigation("TypeUser");
                });

            modelBuilder.Entity("DeIdeas.RouteFlow.API.DAL.Models.ModuleUser.USR_UserRol", b =>
                {
                    b.HasOne("DeIdeas.RouteFlow.API.DAL.Models.ModuleUser.USR_Rol", null)
                        .WithMany()
                        .HasForeignKey("Rol")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DeIdeas.RouteFlow.API.DAL.Models.ModuleUser.USR_Rol", "RolNavigation")
                        .WithMany()
                        .HasForeignKey("RolNavigationRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeIdeas.RouteFlow.API.DAL.Models.ModuleUser.USR_User", null)
                        .WithMany()
                        .HasForeignKey("User")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DeIdeas.RouteFlow.API.DAL.Models.ModuleUser.USR_User", "UserNavigation")
                        .WithMany()
                        .HasForeignKey("UserNavigationUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RolNavigation");

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("DeIdeas.RouteFlow.API.DAL.Models.ModuleUser.USR_TypeUser", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
